# Site settings
title: "nosratheno"
bye_message: "De gustibus non disputandum est"
baseurl: "https://nosratheno.github.io/"
url: "https://nosratheno.github.io"
disqus: nosratheno

# Header settings
nick: "nosratheno"
mail:
    domain: "gmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "nosratheno"
blog:
    server: "github.com"
    nick: "nosratheno"
#fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

collections:
  bas:
    output: true
